version: '3.8'
services:
  api:
    image: clue/json-server
    container_name: smarthome-api
    ports:
      - "3000:80"
    volumes:
      - ./db.json:/data/db.json
    command: --remote --host 0.0.0.0

  appsmith:
    image: index.docker.io/appsmith/appsmith-ce
    container_name: smarthome_ui
    restart: always
    ports:
      - "8090:80"
    volumes:
      - ./appsmith-data:/appsmith-stacks